# Generated by Django 2.2 on 2019-05-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('formed', models.CharField(max_length=256)),
                ('years_active', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
                ('themes', models.CharField(max_length=256)),
                ('last_label', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
